# -*- coding: utf-8 -*-
"""dlsite_ranking

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtqE_KMjcjDc_U7Hrd4j3rOd-Uj9EZmD
"""

# ファイル名：dlsite_ranking.py
# 必要なモジュールをインストール（requests, gspreadなど）
# DLsiteランキングを取得し、スプレッドシートに保存

# ファイル名：dlsite_ranking.py

# 必要なモジュールをインストール
!pip install gspread requests oauth2client

import requests
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import datetime

# DLsiteランキングデータを取得（例：仮のAPIを想定）
def fetch_dlsite_ranking():
    url = 'https://example.com/dlsite-ranking'  # 実際はスクレイピングやAPI
    res = requests.get(url)
    return res.json()

# スプレッドシートに保存
def save_to_spreadsheet(data):
    scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
    creds = ServiceAccountCredentials.from_json_keyfile_name('your-credentials.json', scope)
    client = gspread.authorize(creds)

    sheet = client.open("DLsiteランキング出力").sheet1
    sheet.update('A1', [["タイトル", "サークル", "価格"]])
    for i, item in enumerate(data, start=2):
        sheet.update(f"A{i}", [[item["title"], item["circle"], item["price"]]])

# メイン処理
ranking_data = fetch_dlsite_ranking()
save_to_spreadsheet(ranking_data)