name: Run Colab Daily

on:
  schedule:
    - cron: '0 20 * * *'  # 毎日日本時間5:00（UTCで20:00）に実行
  workflow_dispatch:

jobs:
  run-colab:
    runs-on: ubuntu-latest

    steps:
      - name: Run Colab Notebook
        run: |
 　　　　  curl -L https://raw.githubusercontent.com/douonblog/dlsite-ranking-bot/main/dlsite_ranking_colab.py | python3

#　再保存のためのコメント
#　再保存のためのコメント
