name: Run Colab Daily

on:
  schedule:
    - cron: '0 20 * * *' # 日本時間5:00（UTC 20:00）
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python dlsite_ranking_colab.py
